3.6.15:
  base_image:
    name: buildkite-integration-base
    source: aws
  docker_args:
    PYTHON_VERSION: 3.6.15
3.7.12:
  base_image:
    name: buildkite-integration-base
    source: aws
  docker_args:
    PYTHON_VERSION: 3.7.12
3.8.12:
  base_image:
    name: buildkite-integration-base
    source: aws
  docker_args:
    PYTHON_VERSION: 3.8.12
3.9.10:
  base_image:
    name: buildkite-integration-base
    source: aws
  docker_args:
    PYTHON_VERSION: 3.9.10
3.10.4:
  base_image:
    name: buildkite-integration-base
    source: aws
  docker_args:
    PYTHON_VERSION: 3.10.4
