3.6.15:
  base_image:
    name: buildkite-integration-base
    source: aws
3.7.13:
  base_image:
    name: buildkite-integration-base
    source: aws
3.8.13:
  base_image:
    name: buildkite-integration-base
    source: aws
3.9.12:
  base_image:
    name: buildkite-integration-base
    source: aws
3.10.4:
  base_image:
    name: buildkite-integration-base
    source: aws
